//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunTranslation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translations
    {
        public int TranslationID { get; set; }
        public string OriginalText { get; set; }
        public string TranslatedText { get; set; }
        public Nullable<System.DateTime> TranslationTime { get; set; }
    }
}
